version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server
    restart: always
  proxypool:
    build: .
    image: "498330580/proxypool"
    container_name: proxypool
    ports:
      - "5555:5555"
    volumes:
      - ./proxypool/crawlers/private:/app/proxypool/crawlers/private
      - ./logs:/app/logs
    restart: always
    environment:
      PROXYPOOL_REDIS_HOST: redis
      
